en:
  title: Services
  services:
    design:
      title: Design
      content: We deliver a user-friendly mobile design and web experience to make your clients love it.
    prototype:
      title: Software prototyping
      content: We create clickable apps prototypes to help you pitch your ideas to investors.
    web_app:
      title: Web apps
      content: We design and develop custom web apps to make your ideas work.
    mobile_app:
      title: Mobile apps.
      content: We create native and cross platform iOS and Android apps to make your business mobile.
    dev_ops:
      title: Dev Ops
      content: We automate delivery process and infrastructure changes to speed up time-to-market.
    qa:
      title: QA
      content: We ensure the timely release of working software to get a positive users feedback.
ru:
  title: Услуги
  services:
    design:
      title: Дизайн
      content: Предостовляем свой опыт в разработке дизайн для Web и мобильный решений, которые нравятся нашим клиентам
    prototype:
      title: Прототипирование приложений
      content: Создаем прототипы приложений, которые помогают уловить идею вашими инвесторами
    web_app:
      title: Интернет приложения
      content: Проектируем и разрабатываем интернет приложения, заставляя работать ваши идеи
    mobile_app:
      title: Мобильные приложения.
      content: Создаем родные и кросс-платформенные IOS, Android приложения, делая ваш бизнес мобильным
    dev_ops:
      title: Dev Ops
      content: Автоматизируем процесс доставки измений и изменения инфраструктуры, ускоряя процесс обновления продукта
    qa:
      title: QA
      content: Обеспечиваем переодический выход приложения, получая позитивный отзыв от клиентов
